### PR TITLE
fix build for unavailable dependency 

### PR DESCRIPTION
**Pull request by nezda**
- encountered https://github.com/etorreborre/specs2/issues/295 , using suggested resolution
  - alternative solution to only depend on "specs2-core" didn't work because tests need full specs2 (`TextFileSpec` needs `org.specs2.mock._`)

### CODE REVIEW

**Comment by pmandera** [comment]
Hi Nezda, thank you for your contribution! I will take a look at it and merge in a few days.

**Comment by nezda** [comment]
Hi @pmandera - neat project - some seriously concise, advanced Scala!  The `implicit object` constructs are clever.

I wonder if it would make sense to default the random seed to 0 so results are deterministic?  Maybe add another Config option to allow use of a random seed?

**Comment by nezda** [comment]
@pmandera seems like `_*` on https://github.com/nezda/duometer/blob/c123959c078caaa02332cd5be0bc55b992561c05/src/main/scala/com/pawelmandera/duplicates/MinHashDetection.scala#L30 should be removed and the pattern should fail if there are not 2 items in the set returned by `candidates`?

**Comment by pmandera** [comment]
@nezda I am glad that you like the project and I am looking forward to your contributions ;) The project was developed for my own needs but I know about some people using it in their research.

I am not sure about setting the seed to 0. Some users will be surprised to see a probabilistic algorithm produce the same result each time. Currently it is possible to set a random seed using a -r option. Do you know about similar projects that would use a fixed seed by default?

`_*` in `MinHashDetection.detect` indeed should fail when if there are not 2 items in the set. Any ideas how this should be implemented in an idiomatic way?

**Comment by nezda** [comment]
@pmandera I see your point RE user expectations for probabilistic algorithm and I'll see if I can find an example of other similar tools supporting my view that non-determinism might be confusing.  Closest thing that comes to mind for me is how some people prefer [LinkedHashSet](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashSet.html) over [HashSet](https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html) to get benefits of hashing and determinism of insertion order (at the expense of some RAM) to make debugging / analysis more simple / stable.

I believe just leaving `, _*` off will suffice to have pattern match only length 2 lists.  I made a little spec

``` scala
  "Pattern matching" should {
    def onlyLength2Lists(list: List[Int]): String = list match {
      case List(x, y) => "OK"
      case _ => "NOT"
    }

    "be able to enforce length" in {
      onlyLength2Lists(List()) must_== "NOT"
      onlyLength2Lists(List(1)) must_== "NOT"
      onlyLength2Lists(List(1, 2)) must_== "OK"
      onlyLength2Lists(List(1, 2, 3)) must_== "NOT"
    }
  }
```

There are more complicated alternatives with custom code but that seems good to me.

**Comment by nezda** [comment]
Using `hashCode` as an approximation of `equals` 
https://github.com/nezda/duometer/blob/c123959c078caaa02332cd5be0bc55b992561c05/src/main/scala/com/pawelmandera/duplicates/MinHashCandidates.scala#L12 seems questionable to me: maybe `iter.toSet.iterator` or `iter.toStream.distinct.iterator` (would preserve order)?

**Comment by pmandera** [comment]
Merged.

@nezda `MinHashCandidates.distinctIter` often has to deal with a huge number of elements in the iterator with many duplicates. I tried to avoid reading all the elements into memory simultaneously. I agree that your solutions would be more elegant but this is where I was hitting memory limits.

**Pull request merged**
